### ISSUE TITLE
reports: 20191121 Africa Fintech Summit in Addis Ababa, Ethiopia

### ISSUE THREAD

**Issue by nottrunner** [decredcommunity/events#27]
Here is the link to the draft report. Please review for formatting and typos.
https://gist.github.com/nottrunner/d58a89dbbb4cba5f5c74534b8f6116bf

**Comment by xaur** [comment]
Great report and nice connections @nottrunner !

There are couple formatting bugs and typos but I can fix those. Would you like me to make a pull request out of this gist and proceed with my standard flow?

**Comment by nottrunner** [comment]
Yes please re: proceeding.  I figured there would be formatting issues :)

**Comment by xaur** [comment]
Ok let's move this to #28
