### ISSUE TITLE
reports: 20200204 Africa Tech Summit in Kigali, Rwanda

### ISSUE THREAD

**Issue by nottrunner** [decredcommunity/events#44]
![Pic 1](https://user-images.githubusercontent.com/17677506/74612935-11cc9680-50d8-11ea-8baa-7df893fa9b60.jpg)

![Pic 2](https://user-images.githubusercontent.com/17677506/74612941-17c27780-50d8-11ea-867b-eeab721eef5b.jpg)

![Pic 3](https://user-images.githubusercontent.com/17677506/74612946-1e50ef00-50d8-11ea-8f01-314a774a5575.jpg)

![Pic 4](https://user-images.githubusercontent.com/17677506/74612950-2446d000-50d8-11ea-9002-8df04fa97989.jpg)

![Pic 5](https://user-images.githubusercontent.com/17677506/74612958-3b85bd80-50d8-11ea-93ce-f2fcd8b0beee.jpg)

![Pic 6](https://user-images.githubusercontent.com/17677506/74612966-42accb80-50d8-11ea-972b-e264fb809aa9.jpg)

![Pic 7](https://user-images.githubusercontent.com/17677506/74612974-48a2ac80-50d8-11ea-876c-35a5ad2c5f99.jpg)

![Pic 8](https://user-images.githubusercontent.com/17677506/74613038-e26a5980-50d8-11ea-9b84-f47f2ce25e00.JPG) " "Akin and Collins"

**Comment by xaur** [comment]
Beautiful photos! Linked in #43
