### ISSUE TITLE
index: 20200805 Governance and blockchain in Latin America

### ISSUE THREAD

**Issue by xaur** [decredcommunity/events#58]
@3lian so let's start our "lightweight reports" experiment :)

Please review:

https://github.com/decredcommunity/events/blob/index/index/1599771265.yml

and let me know if all fields look good and what you think of the format.

I designed this format to balance between being readable by humans, relatively easy to fill from a template, and relatively easy to build some automated goodness upon (e.g. list events by month, by country or people involved)

**Comment by 3lian** [comment]
hi bee, works perfect, I'll start using with our next events and grab details from previous ones.

**Comment by xaur** [comment]
In master now https://github.com/decredcommunity/events/blob/master/index/20200805.1.yml
