### ISSUE TITLE
index: 20200811 Decred Talk 1 (pt)

### ISSUE THREAD

**Issue by xaur** [decredcommunity/events#66]
@michae2xl please review:

https://github.com/decredcommunity/events/blob/index/index/1599773576.yml

Did I fill everything correctly? Do you want to change/add any interesting details?

**Comment by Michae2xl** [comment]
Everything is correct, however I think we can add Instagram live which was a new experiment as well.

The **main goal** was to give unknown community members to talk with us and ask questions, to bring them close, so it called: Decred Talk.

**Comment by xaur** [comment]
@Michae2xl thanks for reviewing.

> however I think we can add Instagram live which was a new experiment as well

Do you mean another event here that took place on Aug 17 on Instagram?

**Comment by xaur** [comment]
@Michae2xl so if you did mean that other event I have indexed it too:

https://github.com/decredcommunity/events/blob/index/index/1599776570.yml

feel free to post any additional info and I'll add it too.

**Comment by Michae2xl** [comment]
Thank you, that's it

**Comment by xaur** [comment]
Ok. I updated description of the second one a bit. Next I'll make some tweaks of the first batch of these events entries and move them to the master branch.

**Comment by xaur** [comment]
Both entries are in master now:

https://github.com/decredcommunity/events/blob/master/index/20200811.1.yml

https://github.com/decredcommunity/events/blob/master/index/20200817.1.yml
